# Generated by Django 3.2.7 on 2022-05-24 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electronico')),
                ('es_estudiante', models.BooleanField(default=False, verbose_name='Estudiante status')),
                ('es_institucion', models.BooleanField(default=False, verbose_name='Institución status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoIdent', models.CharField(choices=[('TD', 'Tarjeta de identidad')], max_length=50)),
                ('identificacion', models.BigIntegerField()),
                ('nombres', models.CharField(default='', max_length=50)),
                ('apellidos', models.CharField(default='', max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('barrio', models.TextField()),
                ('localidad', models.TextField()),
                ('telefono', models.BigIntegerField(null=True)),
                ('nivelSisben', models.PositiveSmallIntegerField()),
                ('puntajeSisben', models.FloatField()),
                ('eps', models.CharField(max_length=30)),
                ('tipoSanguinio', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=50)),
                ('rh', models.CharField(choices=[('Positivo', '+'), ('Negativo', '-')], max_length=50)),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Sin definir', 'Sin definir')], max_length=50)),
                ('matriculado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomAcu', models.CharField(max_length=50)),
                ('ideAcu', models.BigIntegerField()),
                ('direccionAcu', models.TextField()),
                ('fechaNacAcu', models.DateField()),
                ('telAcu', models.BigIntegerField(null=True)),
                ('nomPadre', models.CharField(max_length=50, null=True)),
                ('idePadre', models.BigIntegerField(null=True)),
                ('correoPadre', models.EmailField(max_length=254, null=True)),
                ('telPadre', models.BigIntegerField(null=True)),
                ('nomMadre', models.CharField(max_length=50, null=True)),
                ('ideMadre', models.BigIntegerField(null=True)),
                ('correoMadre', models.EmailField(max_length=254, null=True)),
                ('telMadre', models.BigIntegerField(null=True)),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acudiente', to='authApp.estudiante')),
            ],
        ),
    ]
