# Generated by Django 3.2.7 on 2022-05-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
