# Generated by Django 4.0.4 on 2022-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Sin definir', 'Sin definir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rh',
            field=models.CharField(choices=[('Positivo', '+'), ('Negativo', '-')], max_length=50),
        ),
    ]
