# Generated by Django 3.2.7 on 2022-05-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20220524_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idCol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreInsti', models.CharField(max_length=50, unique=True)),
                ('descripcionInsti', models.TextField()),
                ('direccionInsti', models.TextField()),
                ('barrioInsti', models.TextField()),
                ('localidadInsti', models.TextField()),
                ('correoInsti', models.EmailField(max_length=254, null=True)),
                ('telefonoInsti', models.BigIntegerField(null=True)),
                ('telefonoFijoInsti', models.BigIntegerField(null=True)),
                ('nit', models.BigIntegerField(unique=True)),
                ('codigoDANE', models.BigIntegerField(unique=True)),
                ('tipoZona', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=50)),
                ('sectorInsti', models.CharField(choices=[('Privado', 'Privado'), ('Oficial', 'Oficial')], max_length=50)),
                ('nombreRector', models.CharField(default='', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
