# Generated by Django 3.2.7 on 2022-05-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_acudiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='estudiante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acudiente', to='authApp.estudiante'),
        ),
    ]
