# Generated by Django 4.0.4 on 2022-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_acudiente_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='matriculado',
            field=models.BooleanField(default=False),
        ),
    ]
