# Generated by Django 4.0.4 on 2022-05-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_estudiante_matriculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(default='', max_length=50),
        ),
    ]
